tasks:
  - init: pip install -r requirements.txt #poetry install
    command: poetry run python3 -m python_hello_world
  - name: az
    init: |
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      az login --use-device-code